name: Build and deploy ASP.Net Core app to Azure Web App - BMICalculator

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full checkout

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build BMI Calculator project
        run: dotnet build --configuration Release
        
      - name: Run unit tests
        run: dotnet test BMIUnitTestProject/BMIUnitTestProject.csproj --no-restore

      - name: Build Selenium Tests
        run: dotnet build SeleniumTest/SeleniumTest.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # Run Selenium tests with exception handling
      - name: Run Selenium tests
        run: dotnet test SeleniumTest/SeleniumTest.csproj --settings:SeleniumTest.runnsettings --logger:"trx;LogFileName=selenium.trx"
        continue-on-error: true  # Allow the workflow to continue even if this step fails
  
      # Upload results of selenium tests
      - uses: actions/upload-artifact@v4
        with:
          name: Selenium Tests Results
          path: TestResults/selenium.trx

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D602327AAE241A88A161AA446575F02 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5553207D847548558507F229A30F2829 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7748C89998FE49FFBDCF3366BEC1F34B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BMICalculator'
          slot-name: 'Production'
          package: myapp
