name: Build, Test, and Deploy ASP.Net Core app to Azure Web App - BMICalculator

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures a full history fetch to assist with versioning and logging

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build Application
        run: dotnet build --configuration Release

      - name: Run Unit Tests
        run: dotnet test BMIUnitTestProject/BMIUnitTestProject.csproj --no-restore

      - name: Publish Application
        run: dotnet publish -c Release -o myapp

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: myapp

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write # This is required for requesting the JWT during deployment

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

     

      # Run Selenium tests to validate the deployment before production swap
      - name: Run Selenium Tests
        run: |
          dotnet test myapp/SeleniumTest/SeleniumTest.dll --logger:"trx;LogFileName=selenium.trx"
        continue-on-error: true  # This ensures that a failed Selenium test doesn’t halt the workflow

      # Upload results of Selenium tests
      - name: Upload Selenium Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Selenium Tests Results
          path: myapp/SeleniumTest/TestResults/selenium.trx

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D602327AAE241A88A161AA446575F02 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5553207D847548558507F229A30F2829 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7748C89998FE49FFBDCF3366BEC1F34B }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BMICalculator'
          slot-name: 'Production'
          package: myapp

      - name: Blue/Green Swap Deployment Slots
        run: |
          az webapp deployment slot swap \
            --name BMICalculator \
            --resource-group MyResourceGroup \
            --slot staging \
            --target-slot production
        continue-on-error: false  # Ensures if the swap fails, the deployment process halts

